name: .NET Corek Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore Packages
      run: nuget restore "M Centers 8.0.sln"

    - name: Build WPF Application (x64)
      run: msbuild MCenters/MCenters.csproj /p:Configuration=Release /p:Platform=x64 && echo path
      
    - name: Publish Artifact (x64)
      uses: actions/upload-artifact@v3
      with:
        name: wpf-app-x64
        path: D:\a\M-Centers-8.0\M-Centers-8.0\MCentersLibrary\x64\Release\

  build-x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore Packages
      run: nuget restore "M Centers 8.0.sln"

    - name: Build WPF Application (x86)
      run: msbuild MCenters/MCenters.csproj /p:Configuration=Release /p:Platform=x86 /t:Rebuild && echo path

    - name: Publish Artifact (x86)
      uses: actions/upload-artifact@v3
      with:
        name: wpf-app-x86
        path: D:\a\M-Centers-8.0\M-Centers-8.0\MCentersLibrary\x86\Release\
